shamefullyHoist: false
strictPeerDependencies: false
autoInstallPeers: true
enablePrePostScripts: true

minimumReleaseAge: 0

overrides:
  minimatch: '>=10.2.1'

allowBuilds:
  '@firebase/util': true
  '@swc/core': true
  esbuild: set this to true or false
  msw: true
  protobufjs: true
  unrs-resolver: true
