name: 'Setup Project'
description: 'Initialize project: checkout, setup Node.js, install dependencies and generate client from OpenAPI spec'

runs:
  using: 'composite'
  steps:
    - name: Set up Node.js
      uses: actions/setup-node@v6
      with:
        node-version-file: '.nvmrc'
        cache: 'pnpm'

    - name: Enable Corepack
      shell: bash
      run: corepack enable

    - name: Install dependencies
      shell: bash
      run: pnpm install --frozen-lockfile

    - name: Generate api client from OpenAPI spec
      shell: bash
      run: pnpm api:gen
